path_to_output_dir: data/clmbr_models/clmbr_sk_h
overwrite: False
transformer_config:
    is_hierarchical: True
    learning_rate:
        - 1e-4
        - 1e-5
        - 1e-6
    rotary_type:
        - per_head
        - global
    n_heads: 12
    n_layers:
        - 12
        - 6
    max_iter: 1000000
