path_to_output_dir: data/clmbr_models/clmbr_stanford_cp
path_to_og_clmbr_data: data/clmbr_models/clmbr_stanford
overwrite: False
transformer_config:
    learning_rate: 1e-5
    max_iter: 1000000
    
   