path_to_output_dir: data/clmbr_models/clmbr_stanford_cp
path_to_og_clmbr_data: data/clmbr_models/clmbr_stanford
overwrite: False
transformer_config:
    learning_rate:
        - 1e-4
        - 1e-5
        - 1e-6
        - 1e-7
        - 1e-8
    max_iter: 10000000
