path_to_output_dir: data/clmbr_finetuned/clmbr_stanford
path_to_clmbr_data: data/clmbr_models/clmbr_stanford
path_to_labels: data/labels
path_to_linear_probe: data/linear_probes/clmbr_stanford
overwrite: True
transformer_config:
    learning_rate:
        - 1e-5
        - 1e-6
    max_iter: 1000000
