path_to_output_dir: data/clmbr_finetuned/motor_sk
path_to_clmbr_data: data/clmbr_models/motor_sk
path_to_labels: data/labels
overwrite: True
transformer_config:
    learning_rate:
        - 1e-4
        - 1e-5
        - 1e-6
        - 1e-7
        - 1e-8
    max_iter: 1000000
