path_to_output_dir: /hpf/projects/lsung/projects/lguo/femr-on-sk/data/clmbr_models/clmbr_stanford_ft_full
path_to_og_clmbr_data: /hpf/projects/lsung/pretrained_models/clmbr_stanford
overwrite: True
finetune_last_layer: False
transformer_config:
    learning_rate:
        - 1e-5
    rotary_type: global
    n_heads: 12
    n_layers: 12
    max_iter: 1000000
    
   