path_to_clmbr_output_dir: data/clmbr_models/clmbr_stanford_cp
path_to_og_clmbr_data: data/clmbr_models/clmbr_stanford
overwrite: True
sample_percentage:
    - 0.001
    - 0.01
    - 0.05
    - 0.1
    - 0.2
    - 0.4
    - 0.8
transformer_config:
    learning_rate:
        - 1e-4
        - 1e-5
        - 1e-6
        - 1e-7
        - 1e-8
    max_iter: 10000000
