path_to_output_dir: data/clmbr_models_for_few_shots/clmbr_sk
overwrite: True
transformer_config:
    learning_rate:
        - 1e-4
        - 1e-5
        - 1e-6
        - 1e-7
        - 1e-8
    rotary_type:
        - per_head
    n_heads: 12
    n_layers: 12
    max_iter: 10000000
