path_to_output_dir: data/adapter_models_few_shots/clmbr_sk
path_to_labels: data/labels
path_to_features: data/features/clmbr_sk
n_iters: 30 # number of models to train using each setting
train_n:
    - 256
    - 512
    - 1024
    - 2048
feature_type: clmbr
overwrite: True
