path_to_output_dir: data/adapter_models_few_shots/clmbr_mimic
path_to_labels: data/labels
path_to_features: data/features/clmbr_mimic
n_iters: 20 # number of models to train using each setting
train_n:
    - 2
    - 4
    - 8
    - 16
    - 32
    - 64
    - 128
    - 256
    - 512
    - 1024
scale_features: False
feature_type: clmbr
overwrite: True
