path_to_output_dir: data/adapter_models_few_shots/count_sk_noextension_gbm
path_to_labels: data/labels
path_to_features: data/features/count_sk_noextension
n_iters: 20 # number of models to train using each setting
model: lightgbm
train_n:
    - 2
    - 4
    - 8
    - 16
    - 32
    - 64
    - 128
    - 256
    - 512
    - 1024
feature_type: count
overwrite: True
