path_to_output_dir: data/adapter_models_few_shots/count_sk_gbm
path_to_labels: data/labels
path_to_features: data/features/count_sk
n_iters: 30 # number of models to train using each setting
model: lightgbm
train_n:
    - 256
    - 512
    - 1024
    - 2048
feature_type: count
overwrite: True
