path_to_output_dir: data/adapter_models_few_shots/count_sk
path_to_labels: data/labels
path_to_features: data/features/count_sk
n_iters: 10 # number of models to train using each setting
train_n: 
    - 2
    - 4
    - 8
    - 16
    - 32
    - 64
    - 128
feature_type: count
overwrite: True

    
    
   