path_to_output_dir: /hpf/projects/lsung/projects/lguo/femr-on-sk/data/evaluate/adapter_models_few_shots
path_to_models: /hpf/projects/lsung/projects/lguo/femr-on-sk/data/adapter_models_few_shots
overwrite: True