path_to_labels: data/labels
path_to_output_dir: data/features/clmbr_stanford_cp
overwrite: True

featurizer_config:
    type: clmbr
    path_to_clmbr_data: data/clmbr_models/clmbr_stanford_cp/CLMBR_learning_rate_1e-5_max_iter_1000000 