path_to_labels: data/labels
path_to_output_dir: data/features/clmbr_sk
overwrite: True

featurizer_config:
    type: clmbr
    path_to_clmbr_data: data/clmbr_models/clmbr_sk/CLMBR_learning_rate_1e-5_max_iter_1000000_n_heads_12_n_layers_12_rotary_type_global    
    
   